# Generated by Django 4.2.11 on 2026-07-13 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntakeVideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[
                            ("TRADE_TEST", "Trade Test"),
                            ("SAFETY_TRAINING", "Safety Training"),
                        ],
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "intake_video_progress",
            },
        ),
        migrations.CreateModel(
            name="IntakePoliceVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Verified",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="police_verifications",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "intake_police_verifications",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="IntakeMedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_blindness", models.BooleanField(default=False)),
                ("vision", models.CharField(blank=True, default="", max_length=20)),
                ("vertigo", models.BooleanField(default=False)),
                ("blood_type", models.CharField(blank=True, default="", max_length=5)),
                ("exam_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "intake_medical_records",
                "ordering": ["-exam_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="intakevideoprogress",
            constraint=models.UniqueConstraint(
                fields=("worker", "video_type"), name="uq_worker_video_type"
            ),
        ),
        migrations.AddIndex(
            model_name="intakepoliceverification",
            index=models.Index(
                fields=["worker", "expiry_date"], name="intake_poli_worker__df9475_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intakemedicalrecord",
            index=models.Index(
                fields=["worker", "expiry_date"], name="intake_medi_worker__ba188f_idx"
            ),
        ),
    ]
