# Generated by Django 4.2.11 on 2026-07-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_intakevideoprogress_intakepoliceverification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intakemedicalrecord",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="intake_docs/"),
        ),
        migrations.AddField(
            model_name="intakemedicalrecord",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="intakepoliceverification",
            name="document_file",
            field=models.FileField(blank=True, null=True, upload_to="intake_docs/"),
        ),
        migrations.AddField(
            model_name="intakepoliceverification",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
