# Generated by Django 4.2.11 on 2026-07-17 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_intakemedicalrecord_document_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradeTestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField()),
                ("is_passed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trade_test_attempts",
                "ordering": ["worker", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="TradeTestQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("MECHANICAL", "Mechanical"),
                            ("CIVIL", "Civil"),
                            ("ELECTRICAL", "Electrical"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("question_text", models.TextField()),
                ("image_url", models.TextField(blank=True, default="")),
                ("option_a", models.CharField(max_length=200)),
                ("option_b", models.CharField(max_length=200)),
                ("option_c", models.CharField(max_length=200)),
                ("option_d", models.CharField(max_length=200)),
                (
                    "correct_option",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "trade_test_questions",
            },
        ),
        migrations.AddField(
            model_name="worker",
            name="trade_test_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Not yet taken"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed (locked)"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="IntakeVideoProgress",
        ),
        migrations.AddIndex(
            model_name="tradetestquestion",
            index=models.Index(
                fields=["skill_type"], name="trade_test__skill_t_463e4f_idx"
            ),
        ),
        migrations.AddField(
            model_name="tradetestattempt",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_test_attempts",
                to="intake.worker",
            ),
        ),
        migrations.AddConstraint(
            model_name="tradetestattempt",
            constraint=models.UniqueConstraint(
                fields=("worker", "attempt_number"), name="uq_worker_attempt_number"
            ),
        ),
    ]
