# Generated by Django 4.2.11 on 2026-07-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_tradetestattempt_tradetestquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyTrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress_percentage", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_video",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "safety_training_progress",
            },
        ),
    ]
