# Generated by Django 4.2.11 on 2026-08-09 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_safetytrainingprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "db_table": "skills",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="intakemedicalrecord",
            name="storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="intakepoliceverification",
            name="storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="storage_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PE", "Principal Employer"),
                    ("CONTRACTOR", "Contractor"),
                    ("GATE_SECURITY", "Gate Security"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CandidateProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_encrypted", models.BinaryField(blank=True, null=True)),
                ("phone_encrypted", models.BinaryField(blank=True, null=True)),
                ("email_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "phone_hash",
                    models.BinaryField(blank=True, db_index=True, null=True),
                ),
                (
                    "email_hash",
                    models.BinaryField(blank=True, db_index=True, null=True),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=60
                    ),
                ),
                (
                    "resume_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "parser_provider",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "parse_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "CONTRACTOR"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_profile",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateNameToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.BinaryField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="name_tokens",
                        to="intake.candidateprofile",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_name_tokens",
            },
        ),
        migrations.CreateModel(
            name="CandidateSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_skills",
                        to="intake.candidateprofile",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_skills",
                        to="intake.skill",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_skills",
                "indexes": [
                    models.Index(
                        fields=["skill", "profile"],
                        name="candidate_s_skill_i_cdff6b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="candidateskill",
            constraint=models.UniqueConstraint(
                fields=("profile", "skill"), name="uq_candidate_skill"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["contractor", "category"], name="candidate_p_contrac_da8a9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["contractor", "stream"], name="candidate_p_contrac_229172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="candidateprofile",
            index=models.Index(
                fields=["years_of_experience"], name="candidate_p_years_o_8aad06_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone_hash__isnull", False)),
                fields=("contractor", "phone_hash"),
                name="uq_candidate_contractor_phone",
            ),
        ),
        migrations.AddConstraint(
            model_name="candidateprofile",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email_hash__isnull", False)),
                fields=("contractor", "email_hash"),
                name="uq_candidate_contractor_email",
            ),
        ),
        migrations.AddIndex(
            model_name="candidatenametoken",
            index=models.Index(
                fields=["profile"], name="candidate_n_profile_8369ff_idx"
            ),
        ),
    ]
