# Generated by Django 4.2.11 on 2026-08-14 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0007_pgcrypto_pii"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number_encrypted", models.BinaryField(blank=True, null=True)),
                (
                    "account_number_hash",
                    models.BinaryField(blank=True, db_index=True, null=True),
                ),
                (
                    "ifsc",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=11
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "storage_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="intake.worker",
                    ),
                ),
            ],
            options={
                "db_table": "worker_bank_accounts",
            },
        ),
    ]
