# Generated by Django 4.2.11 on 2026-08-14 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0008_workerbankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectrequirement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectrequirement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requirement_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
