# Generated by Django 4.2.11 on 2026-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0009_projectrequirement_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="photo_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
