# Generated by Django 4.2.11 on 2026-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0010_worker_photo_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirementmaster",
            name="kind",
            field=models.CharField(
                choices=[
                    ("DOCUMENT", "Document the worker holds"),
                    ("PILLAR", "Intake pillar the platform tracks"),
                ],
                db_index=True,
                default="DOCUMENT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="requirementmaster",
            name="pillar_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEDICAL", "Medical Exam"),
                    ("POLICE", "Police Verification"),
                    ("TRADE_TEST", "Trade Test"),
                    ("SAFETY_VIDEO", "Safety Training Video"),
                    ("RESUME", "Resume on file"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
